const div1 = dom.create('<div id="test4"><div><div>你好</div></div></div>')
console.log(div1)
dom.body(div1)
dom.before(test4, test)
dom.after(test4, test2)
dom.append(test2, test4)
dom.wrap(test2, test4)
console.log(dom.remove(test5))
console.log(dom.empty(test6))
console.log(dom.attr(test7, 'class'))
dom.attr(test7, 'style', 'color:red,width:100px,height:100px')
console.log(dom.text(test7))
dom.text(test7, 'hello world')
console.log(dom.html(test8))
dom.html(test8, '<div>这是一个div</div>')
dom.style(test8, 'color', 'yellow')
dom.style(test8, 'background-color', 'red')
dom.style(test8, { width: '100px', height: '200px' })
console.log(dom.style(test8, 'background-color'))
dom.class.add(test8, 'blue')
dom.class.remove(test7, 'time')
console.log(dom.class.has(test8, 'blue'))
function listener() {
	console.log(this)
}
dom.on(test7, 'click', listener)
dom.off(test7, 'click', listener) // 移除事件和回调函数时配置参数与dom.on保持一致
dom.on(test7, 'click', listener)
console.log(dom.find('.red', test9))
console.log(dom.find('.red'))
console.log(dom.parent(test4))
console.log(dom.sibling(test2))
console.log(dom.previous(test2))
console.log(dom.next(test2))
dom.each(test9, (node) => console.log(node))
console.log(dom.index(test9))
